### ISSUE TITLE
Packagist repository

### ISSUE THREAD

**Issue by uro** [mi-schi/phpmd-extension#5]
Hello

Do you consider adding this package to Packagist repository?

**Comment by mi-schi** [comment]
Yes oft cause it is possible. But it makes no sense for me, because you can download the phar file. It is a standalone executable wrapper for phpmd.

So, why do you need it on packagist?

**Comment by uro** [comment]
It simple, I don't really want to add `tooly-composer-script` to my project and I'd like to use your repository with automatic builds. 
It also giving me knowledge about changes/releases in your repository which are very important

**Comment by mi-schi** [comment]
It is better to separate the check code from the production code. The advatages:

* no dependencies 
* simple installation
* install the phars global for all projects

More, see http://stackoverflow.com/questions/3521484/advantages-of-phar-archives-in-php

You can download the phar while the build runs. If you want the latest version, use 

https://github.com/mi-schi/phpmd-extension/releases/download/stable/phpmd-extension.phar

Otherwise

https://github.com/mi-schi/phpmd-extension/releases/download/4.2.0/phpmd-extension.phar

Is it an option for you?

**Comment by keradus** [comment]
@mi-schi 

> It is better to separate the check code from the production code. 

indeed. that's why Composer has `dependencies` and `devDependencies`

> no dependencies

phar dev tool is still a dependency, even if not managed by Composer

> simple installation

as simple as `composer require`

> install the phars global for all projects

and then when 20 devs are working on same project all of them must manually install it globally instead of letting project-specific `composer.json` do all preparations.

-------------

@uro 

add to your `composer.json`
```json
    "repositories": [
        {
            "type": "vcs",
            "url":  "git@github.com:mi-schi/phpmd-extension.git"
        }
    ],
```

it won't work as great as package that exists in package repository, but it will work

---------------------

guys, both point are valid. while one want to go one way, second will go another way.
why not make it easier and let everyone follow process that he likes?

**Comment by uro** [comment]
@keradus I made it on identically way, it's good because we are not loosing any functionality. I just think it could be helpful to have this package in packagist repository.

**Comment by mi-schi** [comment]
Also with composer require --dev you have dependencies to:

* ext-xml
* "symfony/dependency-injection": "^2.3.0|^3"
* "symfony/filesystem": "^2.3.0|^3"
* "symfony/config": "^2.3.0|^3"
* "psr/container": "^1.0"
* "php": ">=5.5.9"

in your dev environment. Your production environment operates with other dependencies.

We had this problems in our company. The testing and check tools interfere the update possibilities of the project dependencies. You have to update all the dependencies in your require-dev repositories (or create a github issue if it is external) to update the project dependencies.
Also the application on the staging and live system interact different than in dev mode. You will waste a lot of time to find the dependency problem or even worse create a workaround because of deadlines! I only want to protect you from the dependency hell.

If you don't want to integrate the testing and check tools in your CI and you really want to use composer for the download: The best way in my opinion is to create a second composer.json for the testing and check dependencies.

I add phpmd-extension to packagist (https://packagist.org/packages/mi-schi/phpmd-extension) and update the readme. Thanks for the discussion and recapitulate this subject.

**Comment by uro** [comment]
@mi-schi Good to know, and thank you for adding your package to Packagist!

For me you could close this issue.

**Comment by keradus** [comment]
in most cases deps vs devDeps are enough in composer. no need for extra composer file.

**Comment by glensc** [comment]
he's probably speaking when project deps and extension deps conflict. like symfony deps.
